name: Go deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-versions: 1.17
      - name: Test
        run: go test -v ./...
  deploy:
    runs-on: ubuntu-latest
    needs: test # 上のtest jobが終了してからdeployジョブを行うという直列
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx # イメージビルドにBuildKit有効化
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image # #GITHUB_REFはブランチ名なの？
        run: |
          TAG=$(echo $GITHUB_REF | grep -o "[0-9][¥.].*")
          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/greeting:$TAG
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE
