name: Go test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # check out
      - uses: actions/checkout@v2
      # set up
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-versions: 1.17
      # build ...とは？
      - name: Build
        # ./... はワイルドカードで　再起的やって。https://jablogs.com/detail/7789
        run: go build -v ./... # -v => print the names of packages as they are compiled.
      # test
      - name: Test
        run: go test -v ./...
